yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'
# Для Андрея: да эту переменную мы используем в yatube/urls.py

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы',
        help_text='Введите название группы',
    )
    slug = models.SlugField(unique=True)
    description = models.TextField(
        verbose_name='Описание группы',
        help_text='Введите описание группы',
    )

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self) -> str:
        return self.title[:30]


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[:30]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE,
        verbose_name='Текст поста'
    )
    author = models.ForeignKey(
        User,
        related_name='comments',
        on_delete=models.SET_NULL,
        verbose_name='Автор',
        null=True
    )
    text = models.TextField(
        help_text='Текст нового комментария',
        verbose_name='Текст коментария'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self) -> str:
        return self.text[:30]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        verbose_name='Подписчик',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        verbose_name='Подписка',
        on_delete=models.CASCADE
    )

    def __str__(self) -> str:
        return f'Подписка {self.user} на {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def get_page_context(queryset, request):
    paginator = Paginator(queryset, settings.PAGIN)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    page_obj = get_page_context(Post.objects.select_related('group').all(),
                                request)
    context = {'page_obj': page_obj}
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = get_page_context(posts, request)
    context = {
        'page_obj': page_obj,
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = get_page_context(posts, request)
    following = False
    if request.user != author:
        Follow.objects.filter(user__id=request.user.id, author=author).exists()
        following = True
    context = {
        'page_obj': page_obj,
        'posts': posts,
        'author': author,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    form = CommentForm()
    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    context = {'form': form}
    if request.method != 'POST':
        return render(request, 'posts/create_post.html', context)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', context)
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', request.user.username)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    context = {
        'form': form,
        'is_edit': True,
        'post': post,
    }
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    if request.method != 'POST':
        return render(request, 'posts/create_post.html', context)
    if not form.is_valid():
        context = {
            'form': form,
            'is_edit': True,
        }
        return render(request, 'posts/create_post.html', context)
    form.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = get_page_context(posts, request)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = get_page_context(posts, request)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': True
    }
    return render(request, 'posts/profile.html', context)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    Follow.objects.filter(user=request.user, author=author).delete()
    page_obj = get_page_context(posts, request)
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': False
    }
    return render(request, 'posts/profile.html', context)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if not is_edit %}
    Добавить пост  
  {% else %} 
    Редактировать пост
  {% endif %}
{% endblock %} 
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
          {% if not is_edit %}
            Добавить пост  
          {% else %} 
            Редактировать пост
          {% endif %}
        </div>
          <div class="card-body">        
            <form method="post" enctype="multipart/form-data" action="{% if not is_edit %}
                                                                        {% url 'posts:post_create'%}
                                                                      {% else %}
                                                                        {% url 'posts:post_edit' post.id%}
                                                                      {% endif %}">                 
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group">
                  {% if field.errors %}
                    <div class="alert.alert.danger">
                      {{ field.errors }}
                    </div>
                  {% endif %}
                  {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                  {% endif %}
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if not is_edit %}
                    Добавить  
                  {% else %} 
                    Сохранить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
      </div>
    </div>
  </div>
{% endblock %} 

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}
  Последние обновления избранных авторов
{% endblock %}
{% block content %}
  <h1>Последние обновления избранных авторов</h1>
  <article>
    {% cache 20 follow_page %}
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'includes/post.html' %}
      {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% endcache %}
      {% include 'posts/includes/paginator.html' %}
  </article>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
  <h1> {{ group.title }} </h1>
    <p> {{ group.description }} </p>
    <article>
      {% for post in page_obj %}
        {% include 'includes/post.html' %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}        
    </article>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  <h1>Последние обновления на сайте</h1>
  <article>
    {% include 'posts/includes/switcher.html' %}
    {% cache 20 index_page page_obj %}
    {% for post in page_obj %}
      {% include 'includes/post.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% endcache %}
    {% include 'posts/includes/paginator.html' %}
  </article>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load user_filters %}
{% load thumbnail %}
{% block title %}
Пост {{ post|truncatechars:"30" }}
{% endblock %}
{% block content %}
  <main>
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}  
            <li class="list-group-item">
              Группа: {{ post.group }}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
            </li>
          {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ post.author.posts.count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author.username %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
          {% if request.user == post.author %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            Редактировать пост
          </a>
          {% endif %}
          {% include 'posts/includes/add_comment.html'%}
      </article>
    </div> 
  </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
<div class="mb-5">
  <h1>Все посты пользователя {{ author.get_full_name }}</h1>
  <h3>Всего постов: {{ posts_count }}</h3>
  {% if request.user != author %}
  {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
   {% endif %}
   {% endif %}
</div>
  <article>
  {% for post in page_obj %}
    <ul>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }} 
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}  
    <p>
      {{ post.text|truncatewords:30 }}
    </p>
    <a href="{% url 'posts:post_detail' post.pk%}">подробная информация </a>
    <br>
  </article>
  <br>
  {% if post.group %} 
    <p>Группа: {{ group.title }}</p>        
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}      
  <hr>
  {% endfor %}
  {% if forloop.last %}<hr>{% endif %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}